version: '3'
services:

  app:
    build:
      context: .
      dockerfile: "Dockerfile_production"
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/mens_cosme_api
      - public-data:/mens_cosme_api/public
      - tmp-data:/mens_cosme_api/tmp
      - log-data:/mens_cosme_api/log
    ports:
      - "5000:5000"

  web:
    build:
      context: ./docker/nginx
      dockerfile: "Dockerfile_production"
    volumes:
      - public-data:/mens_cosme_api/public
      - tmp-data:/mens_cosme_api/tmp
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
