version: '3'
services:
  db:
    image: mysql:5.6.47
    environment:
      - ./docker/mysql/environments/db.env
    volumes:
      - ./docker/mysql/volumes:/var/lib/mysql
    ports:
      - "4306:3306"

  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/mens_cosme_api
      - public-data:/mens_cosme_api/public
      - tmp-data:/mens_cosme_api/tmp
      - log-data:/mens_cosme_api/log
      - gem_data:/usr/local/bundle
    ports:
      - "5000:5000"
    depends_on:
      - db

  web:
    build: ./docker/nginx
    volumes:
      - public-data:/mens_cosme_api/public
      - tmp-data:/mens_cosme_api/tmp
    ports:
      - "7000:80"
    depends_on:
      - app

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
  gem_data: