version: '3'
services:
  db:
    image: mysql:5.6.47
    environment:
      - ./docker/mysql/environments/db.env
    volumes:
      - ./docker/mysql/volumes:/var/lib/mysql
    ports:
      - "4306:3306"

  app:
    build: .
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5000 -b '0.0.0.0'"
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/mens_cosme_api
      - public-data:/mens_cosme_api/public
      - tmp-data:/mens_cosme_api/tmp
      - log-data:/mens_cosme_api/log
    ports:
      - "5000:5000"
    depends_on:
      - db

  web:
    build: ./docker/nginx
    volumes:
      - public-data:/mens_cosme_api/public
      - tmp-data:/mens_cosme_api/tmp
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: